"""Create message table

Revision ID: 017d0f9fe218
Revises: 6bf24561f36f
Create Date: 2025-05-29 20:26:11.309663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017d0f9fe218'
down_revision = '6bf24561f36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_sid_key', type_='unique')
        batch_op.drop_column('sid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('message_sid_key', ['sid'])

    # ### end Alembic commands ###
