"""Create message table

Revision ID: 6bf24561f36f
Revises: 
Create Date: 2025-05-29 20:13:05.053303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf24561f36f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=64), nullable=False),
    sa.Column('from_user', sa.String(length=100), nullable=False),
    sa.Column('ai_task', sa.JSON(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
