"""Create message table

Revision ID: 98593f87aa97
Revises: 017d0f9fe218
Create Date: 2025-05-29 20:32:34.788847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98593f87aa97'
down_revision = '017d0f9fe218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['sid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sid')

    # ### end Alembic commands ###
