"""Add Twilio credentials to user

Revision ID: bb8c96fdefa1
Revises: f03b19ea6dee
Create Date: 2025-05-30 21:51:14.374779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8c96fdefa1'
down_revision = 'f03b19ea6dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twilio_sid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twilio_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twilio_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('twilio_number')
        batch_op.drop_column('twilio_token')
        batch_op.drop_column('twilio_sid')

    # ### end Alembic commands ###
